# Use Node 18
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the code
COPY . .

# Expose port used by Render
EXPOSE 10000

# Start the app
CMD ["npm", "start"]
